name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2022-09-28
version: '9.3.22'
project: 'drupal'
datestamp: 1664382735
